name: JOMO Daily Draw Mainnet 🎲

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  draw_winner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute Mainnet Draw
        env:
          NEAR_KEY: ${{ secrets.NEAR_MAINNET_PRIVATE_KEY }}
        run: |
          npx near-cli-rs@latest contract call-function as-transaction pool-dapp-jomo.near draw_winner json-args '{}' prepaid-gas '100.0 Tgas' attached-deposit '0 NEAR' sign-as crypto-jomo.near network-config mainnet sign-with-plaintext-private-key "${{ secrets.NEAR_MAINNET_PRIVATE_KEY }}" send